/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MwcAppBar {

    }
  }

  interface HTMLMwcAppBarElement extends StencilComponents.MwcAppBar, HTMLStencilElement {}

  var HTMLMwcAppBarElement: {
    prototype: HTMLMwcAppBarElement;
    new (): HTMLMwcAppBarElement;
  };
  interface HTMLElementTagNameMap {
    'mwc-app-bar': HTMLMwcAppBarElement;
  }
  interface ElementTagNameMap {
    'mwc-app-bar': HTMLMwcAppBarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'mwc-app-bar': JSXElements.MwcAppBarAttributes;
    }
  }
  namespace JSXElements {
    export interface MwcAppBarAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MwcApp {
      'background': string;
      'primary': string;
      'secondary': string;
      'surface': string;
      'textOnprimary': string;
      'textOnsecondary': string;
      'textOnsurface': string;
    }
  }

  interface HTMLMwcAppElement extends StencilComponents.MwcApp, HTMLStencilElement {}

  var HTMLMwcAppElement: {
    prototype: HTMLMwcAppElement;
    new (): HTMLMwcAppElement;
  };
  interface HTMLElementTagNameMap {
    'mwc-app': HTMLMwcAppElement;
  }
  interface ElementTagNameMap {
    'mwc-app': HTMLMwcAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'mwc-app': JSXElements.MwcAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MwcAppAttributes extends HTMLAttributes {
      'background'?: string;
      'primary'?: string;
      'secondary'?: string;
      'surface'?: string;
      'textOnprimary'?: string;
      'textOnsecondary'?: string;
      'textOnsurface'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MwcButton {
      'ripple': boolean;
      'tag': string;
    }
  }

  interface HTMLMwcButtonElement extends StencilComponents.MwcButton, HTMLStencilElement {}

  var HTMLMwcButtonElement: {
    prototype: HTMLMwcButtonElement;
    new (): HTMLMwcButtonElement;
  };
  interface HTMLElementTagNameMap {
    'mwc-button': HTMLMwcButtonElement;
  }
  interface ElementTagNameMap {
    'mwc-button': HTMLMwcButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'mwc-button': JSXElements.MwcButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface MwcButtonAttributes extends HTMLAttributes {
      'ripple'?: boolean;
      'tag'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;